[build]
cmds = [
  "pip install --no-cache-dir --timeout=1000 --upgrade pip",
  "pip install --no-cache-dir --timeout=1000 -r requirements-minimal.txt"
]

[start]
cmd = "cd backend && python run.py"

[variables]
PYTHONUNBUFFERED = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[phases.setup]
nixPkgs = ["python312", "gcc", "pkg-config"] 