services:
  # Sentinel Backend API
  - type: web
    name: sentinel-backend
    runtime: python3
    plan: free
    buildCommand: |
      cd backend && pip install -r requirements.txt
    startCommand: |
      cd backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: PORT
        value: 5000
      - key: CORS_ORIGINS
        value: https://sentinel-frontend.vercel.app,https://localhost:3000
      - key: DATABASE_URL
        generateValue: true
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    
  # PostgreSQL Database
  - type: pserv
    name: sentinel-postgres
    plan: free
    env: postgresql
    databases:
      - name: sentinel
        user: sentinel 