services:
  # Backend API Service
  - type: web
    name: sentinel-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "5000"
    healthCheckPath: /health

databases:
  # PostgreSQL Database
  - name: sentinel-postgres
    plan: free 